{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "javaspringboot.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
        {{- include "javaspringboot.labels" . | nindent 4 }}
{{- end -}}
